# Generated by Django 4.1.1 on 2022-10-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task", name="key", field=models.TextField(default=""),
        ),
    ]
