# Generated by Django 4.1.1 on 2022-10-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_task_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="task", name="order", field=models.IntegerField(default=-1),
        ),
    ]
